---
title: "Media Headlines"
author: "by myTinyShinys"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: [ menu ]
    source_code: embed
    css: styles.css
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)

library(gdeltr2)

library(plotly)

mediaChoices <- sort(c("theguardian.com","wsj.com","dailymail.co.uk","bbc.co.uk","espn.com","news.cn","thehindu.com", "orlandosentinel.com","washingtonpost.com", "nytimes.com"))



```

Inputs {.sidebar data-width=325}
-------------------------------------

```{r inc munging}
includeMarkdown("info.md")
hr()

h5("Latest Headlines from the Selected Media") 
h5("Click image for Original Article") 

inputPanel(
radioButtons("source", label="Method of Media Selection", choices=c("From List","Self Input"), inline=T)
)

output$method <- renderUI(
  if(input$source=="From List"){
  selectInput("media_list", "Choose Sources. Click input for more choices", choices=mediaChoices,multiple=T, selected=c("nytimes.com","washingtonpost.com"))
  } else {
    textInput("media_self",label="Enter url(s) of desired media, separated by comma", 
              placeholder="e.g. latimes.com, spiegel.de")
  }
)

 


uiOutput("method")
actionButton("go",label = "Get Articles", icon = NULL, width = '100px')
br()
 em("NB. Sometimes sources are unavailable or old articles get provided") 

info <- eventReactive(input$go,{

  if(input$source=="From List") {

    
  theDomains <- input$media_list
  
  } else {
    
   theDomains <-  str_trim(unlist(str_split(input$media_self,",")))
  }
  print(theDomains)
data <- 
  get_data_ft_api_domains(term = NA, domains = theDomains)



data <- data %>% 
  mutate(urlThumbnail=ifelse(is.na(urlThumbnail),"http://www.premiersoccerstats.com/noImage2.jpg",urlThumbnail)) %>% 
  arrange(desc(dateTimeArticle))





info=list(data=data)
return(info)

})
```

Row {data-height=200}
-----------------------------------------------------------------------


### {.no-title}

```{r}

output$one <- renderUI({
  
   list(
h4(strong(info()$data$titleArticle[1])),
  a(href=info()$data$urlArticle[1], target='_blank', img(src=info()$data$urlThumbnail[1], width= 350))
  )
})

uiOutput("one")
```


### {.no-title}

```{r}

output$two <- renderUI({
 
  list(
h4(strong(info()$data$titleArticle[2])),
  a(href=info()$data$urlArticle[2], target='_blank', img(src=info()$data$urlThumbnail[2], width= 350))
  )
})

uiOutput("two")
```


### {.no-title}

```{r}

output$three <- renderUI({
  
  list(
h4(strong(info()$data$titleArticle[3])),
  a(href=info()$data$urlArticle[3], target='_blank', img(src=info()$data$urlThumbnail[3], width= 350))
  )
})

uiOutput("three")
```


### {.no-title}

```{r}

output$four <- renderUI({
  list(
h4(strong(info()$data$titleArticle[4])),
  a(href=info()$data$urlArticle[4],target='_blank', img(src=info()$data$urlThumbnail[4], width= 350))
  )
})

uiOutput("four")
```


### {.no-title}

```{r}

output$five <- renderUI({
  list(
h4(strong(info()$data$titleArticle[5])),
  a(href=info()$data$urlArticle[5],target='_blank', img(src=info()$data$urlThumbnail[5], width= 350))
  )
})

uiOutput("five")
```



Row {data-height=200}
-----------------------------------------------------------------------


### {.no-title}

```{r}

output$six <- renderUI({
  list(
h4(strong(info()$data$titleArticle[6])),
  a(href=info()$data$urlArticle[6],target='_blank', img(src=info()$data$urlThumbnail[6], width= 350))
  )
})

uiOutput("six")
```


### {.no-title}

```{r}

output$seven <- renderUI({
  list(
h4(strong(info()$data$titleArticle[7])),
  a(href=info()$data$urlArticle[7],target='_blank', img(src=info()$data$urlThumbnail[7], width= 350))
  )
})

uiOutput("seven")
```


### {.no-title}

```{r}

output$eight <- renderUI({
  list(
h4(strong(info()$data$titleArticle[8])),
  a(href=info()$data$urlArticle[8],target='_blank', img(src=info()$data$urlThumbnail[8], width= 350))
  )
})

uiOutput("eight")
```


### {.no-title}

```{r}

output$nine <- renderUI({
  list(
h4(strong(info()$data$titleArticle[9])),
  a(href=info()$data$urlArticle[9],target='_blank', img(src=info()$data$urlThumbnail[9], width= 350))
  )
})

uiOutput("nine")
```


### {.no-title}

```{r}

output$ten <- renderUI({
  list(
h4(strong(info()$data$titleArticle[10])),
  a(href=info()$data$urlArticle[10],target='_blank', img(src=info()$data$urlThumbnail[10], width= 350))
  )
})

uiOutput("ten")
```

Row {data-height=200}
-----------------------------------------------------------------------


### {.no-title}

```{r}

output$eleven <- renderUI({
  list(
h4(strong(info()$data$titleArticle[11])),
  a(href=info()$data$urlArticle[11],target='_blank', img(src=info()$data$urlThumbnail[11], width= 350))
  )
})

uiOutput("eleven")
```


### {.no-title}

```{r}

output$twelve <- renderUI({
  list(
h4(strong(info()$data$titleArticle[12])),
  a(href=info()$data$urlArticle[12],target='_blank', img(src=info()$data$urlThumbnail[12], width= 350))
  )
})

uiOutput("twelve")
```


### {.no-title}

```{r}

output$thirteen <- renderUI({
  list(
h4(strong(info()$data$titleArticle[13])),
  a(href=info()$data$urlArticle[13],target='_blank', img(src=info()$data$urlThumbnail[13], width= 350))
  )
})

uiOutput("thirteen")
```


### {.no-title}

```{r}

output$fourteen <- renderUI({
  list(
h4(strong(info()$data$titleArticle[14])),
  a(href=info()$data$urlArticle[14],target='_blank', img(src=info()$data$urlThumbnail[14], width= 350))
  )
})

uiOutput("fourteen")
```


### {.no-title}

```{r}

output$fifteen <- renderUI({
  list(
h4(strong(info()$data$titleArticle[15])),
  a(href=info()$data$urlArticle[15],target='_blank', img(src=info()$data$urlThumbnail[15], width= 350))
  )
})

uiOutput("fifteen")
```

